# SwiftLint Configuration for MacML
# https://github.com/realm/SwiftLint

# Paths to include
included:
  - Sources
  - Tests

# Paths to exclude
excluded:
  - .build
  - DerivedData
  - Packages

# Disabled rules
disabled_rules:
  - trailing_whitespace  # Can be noisy
  - todo  # We use TODO comments intentionally
  - opening_brace  # Conflicts with some formatting preferences

# Opt-in rules
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule configurations
line_length:
  warning: 150
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - x
    - y
    - z
    - ok
    - lhs
    - rhs
    - lr  # learning rate
    - db  # database
    - tp  # true positive
    - fp  # false positive
    - fn  # false negative

large_tuple:
  warning: 4
  error: 5

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

# Custom rules
custom_rules:
  no_print_in_production:
    name: "No print() in production code"
    regex: '^\s*print\s*\('
    match_kinds:
      - identifier
    message: "Use Logger instead of print() for production code"
    severity: warning

  force_cast_suggestion:
    name: "Force cast warning"
    regex: ' as! '
    message: "Force casting is dangerous. Consider using 'as?' with proper error handling."
    severity: warning
